language: minimal
jobs:
  include:
    - &run_tests
      # Template; subsequent uses modify 'env'
      env:
        - OS_TYPE=centos OS_VERSION=7 BUILD_ENV=osg
      sudo: required
      services:
        - docker
      before_install:
        - sudo apt-get update
        - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
        - sudo service docker restart
        - sleep 5
        - sudo docker pull centos:centos${OS_VERSION}
      script:
        - tests/setup_tests.sh
    - <<: *run_tests
      env:
        - OS_TYPE=centos OS_VERSION=7 BUILD_ENV=uw_build
      deploy:
        - provider: script
          skip_cleanup: true
          script: tests/sftp_upload.sh
          on:
            repo: htcondor/htcondor-ce
            tags: true
